export enum MESSAGE {
  NO_EXISTE = 'NO EXISTE',
  YA_EXISTE_ESTE_SLUG = 'YA EXISTE ESTE SLUG SLUG',
  SE_ELIMINO_CORRECTAMENTE = 'SE ELIMINO CORRECTAMENTE',
  NO_SE_PUEDE_ELIMINAR = 'NO SE PUEDE ELIMINAR',
}
